import Head from "next/head";
import RichEditor from "components/RichEditor";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <RichEditor />
    </div>
  );
}
